[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anvil_db = { path = "../.." }

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[profile.release]
debug = true
